### ISSUE TITLE
modify player save

### ISSUE THREAD

**Issue by cupofdeath** [monkeymanboy/BeatSaberCustomCampaigns#15]
hey not sure if im doing this right i recall you used to be able to mod the player save to skip past a song or reset progress if you wanted to and when i used the file i backed up that i recall used to be my player save it just resets the progress is there anyway to restore the custom campaigns progress or moddify it to unlock up to the point i was at asking as i was almost done with the master one just had to beat 2 or 3 songs to have it fully done before i took a break from vr for a bit

**Comment by cupofdeath** [comment]
any update on this just went back and tried and still couldnt figure it out

**Comment by PulseLane** [comment]
There is no way to restore progress in the current version of CustomCampaigns and I'm not aware of such a thing ever existing.

A new version of CustomCampaigns is very very close to release, and either on release or shortly thereafter there will be a way to automatically pass a level if you have a score on the leaderboard; I'm just still waiting to hear back from some other people about it.

**Comment by PulseLane** [comment]
Done in latest release.
