### ISSUE TITLE
Possible to use your own custom levels?

### ISSUE THREAD

**Issue by PaulBlazek** [monkeymanboy/BeatSaberCustomCampaigns#20]
Is there a way I can just use my own custom levels that aren't on BeatSaver but are already loaded? Is it as simple as filling in the songId with the name of my song or is this not supported?
Thanks!

**Comment by PulseLane** [comment]
If you know the hash of your level you can set the hash in the level to match that. If not, then you can use the songid to match it. 

The way the songid search works is that it looks for the first result in your CustomLevels folder with a name matching the songid + a blank space. e.g. "songid": "9999999" will find a map in your CustomLevels folder with the folder name "9999999 (Example)". So you could prepend some string that you know won't match any other map ids and rename the song folder to match.
