### ISSUE TITLE
Game crash with mission objective Full Combo or Combo n, with allowStandardLevel: true

### ISSUE THREAD

**Issue by tocxx** [monkeymanboy/BeatSaberCustomCampaigns#21]
Experiencing a game crash when I set `allowStandardLevel: true` in the mission json, if my mission's objective is either a full combo or a combo of some sort.
The game logs signify it can't find the `GetBaseGameCheckerForObjective.fullComboMissionObjectiveChecker._scoreController`.
I'm on game version 1.29.1
![Bilde_2023-10-07_004926680](https://github.com/monkeymanboy/BeatSaberCustomCampaigns/assets/132984852/3fdbe48d-faf1-4d4f-a4e2-9bdf86e7876a)

**Comment by PulseLane** [comment]
I made this fix but forgot to merge it in lol. Anyway, it's in latest release now.
