### ISSUE TITLE
Show level names

### ISSUE THREAD

**Issue by boulders2000** [monkeymanboy/BeatSaberCustomCampaigns#4]
This is more of a feature request if anything,

I have a few songs installed that require passing a certain (custom) campaign level, but I have 0 clue where they could be or which ones they are.
So my request is,
Can you make it so that when you hover over the levels it shows the names of those levels? So I can see what I need to work towards instead of trying/passing every single level and finding out I'm in the wrong campaign

**Comment by PulseLane** [comment]
"?" requirements button added a while ago fixed this
