### ISSUE TITLE
Main Banner and back button not showing after playing any level of any custom campaign

### ISSUE THREAD

**Issue by cadavren** [monkeymanboy/BeatSaberCustomCampaigns#7]
hello again !
I noticed I got the campaign banner and the "back" button disappearing after I played levels (more precisely, after using the pause button to get back to level selection, I haven't tried when you finish one). Tho it doesn't soft lock anything, I could still go back, apparently it is just like it's invisible (see screenshots and video for more details).

![20201221214300_1](https://user-images.githubusercontent.com/61839268/102820749-0fad2580-43d6-11eb-9d38-78a94dde72e5.jpg)
![20201221214307_1](https://user-images.githubusercontent.com/61839268/102820762-163b9d00-43d6-11eb-9aae-1816b669e25b.jpg)

EDIT : The video I uploaded wasn't the one I wanted to send, I will re-upload one tomorrow(04/01/2021

let me know if you need anything else.

Have a nice day/night !

**Comment by DekuSkrub2129** [comment]
I have the same issue, it also happens on completing a level, and the invisible button isn't there at all.
I havent been able to progress on any campaign, they all seem to do this

**Comment by PulseLane** [comment]
This issue should be fixed in the latest version - lemme know if you still run into it, though!

**Comment by PulseLane** [comment]
no longer happens in 3.0
